---
title: "First Knit"
author: "Onalee Garusinghe"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation.  

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.   
  
### my answer     
  I went to QuartzHill High School. I graduated in 2023. English is easier for me than math. However, I still  prefer math. I did best in science subjects. My favorite was chemistry or biology.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have a windows computer at home. I would rate myself a 6 on the computer scale. My brother is a 10 though and could help me. My internet connection pretty stable. No interruptions for the majority of time.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I prefer to be called my actual name, Onalee. I have no nicknames that I go by. 
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve? 

### my answer     
  I want to achieve a career in medicine. Ideally, I would like to be a dermatologist. I am a biology major. However, chemistry is the most interesting subject to me. I plan on achieving my bachelor's degree. But ultimately, I would like a doctorate. 
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   The only country I've been to outside of America is Sri Lanka. My parents are both from there originally, so we visit family there. I would never choose to be drafted in the military. It's not a topic that personally interests me.
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   I am taking Math 116. I am taking it to meet some recommended requirements for UCLA, because my counselor told me to. I knew Math 116 counted for transfer institutions because of my counselor. I hope to get an A grade, so that I can transfer to a UC school when I get my associate's degree. 
 






  




